### PR TITLE
Task delivery

### PR DESCRIPTION
**Pull request by daveio**
Here we go then! This is where I am. There's documentation in the README and happy to answer any questions. Let me know where you want to go from here 👍

### CODE REVIEW

**Comment by daveio** [comment]
Hey @adoankim - just to say I've seen your comment, and I'll get some answers written up for you as soon as possible. Thanks for being so thorough!

**Comment by daveio** [comment]
@adoankim 

## Development workflow

> I've tried to deploy it first locally but didn't work without modifying some bits :). This would be useful for devs that don't have access to the Google Cloud resources and others, and just want to test the deployment locally.

#### Please explain briefly how the previous could be supported for the given solution.

I've made modifications to `bin/deploy` to fix the issues. The deployment methodology in use here is not scalable particularly due to the fact that meaningful configuration lives in the deployment script itself, which is a recipe for chaos at scale. Still, in the given solution, it now works properly; after deployment the script patches the image of the deployments, and issues a rollout.

#### And if we would need to deploy a single version, let's say staging, how this could be done?

Similar modifications to the deployment script, which I've not done for the sake of time, but since support exists already to deploy a single environment to GKE, it could be modified similarly to the modifications mentioned above.

## Infrastructure

> The current terraform plan requires that the person that manages it to have privileges for different resources (project vs compute resources).

#### What are the benefits of keeping all the resource management in the same plan? and the advantages of separate it in different ones?

Since Terraform is a declarative model, having everything in the same plan allows it to compute desired state reliably. While portions of state can be imported from one plan into another, changes lose atomicity and complicate any guarantees, in turn complicating any automation or CI processes; it becomes possible to apply one plan but for another to fail. With everything in one plan, changes either apply or they don't.

> Applying the Terraform plan from a clean project I got the following errors. I've fixed it by adding "something" extra on those resources.
>
> Hint: There is a *dependency* between the permissions and the usage of the resources.

    Error: Error creating Dataset: googleapi: Error 400: The project munraito-00001
    has not enabled BigQuery., invalid

    on main.tf line 131, in resource "google_bigquery_dataset" "k8s_usage":
    131: resource "google_bigquery_dataset" "k8s_usage" {


    Error: Error creating KeyRing: googleapi: Error 400: Google Cloud KMS API
    has not been used in this project before, or it is disabled. Enable it by visiting
    https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=954764994050
    then retry. If you enabled this API recently, wait a few minutes for the action
    to propagate to our systems and retry.

    on main.tf line 141, in resource "google_kms_key_ring" "k8s-primary":
    141: resource "google_kms_key_ring" "k8s-primary" {


    Error: Error creating ManagedZone: googleapi: Error 403: Google Cloud
    DNS API has not been used in project 954764994050 before or it is disabled.
    Enable it by visiting
    https://console.cloud.google.com/apis/api/dns.googleapis.com/overview?project=954764994050
    then retry. If you enabled this API recently,  wait a few minutes for the action to
    propagate to our systems and retry.,  accessNotConfigured

    on main.tf line 171, in resource "google_dns_managed_zone" "feeld-env":
    171: resource "google_dns_managed_zone" "feeld-env" {

#### How could we solve this dependency?

Explicit dependencies could be added using the `depends_on` operator. Usually dependencies are implicitly managed by the module, but in cases like this where those implicit dependencies are missing, Terraform won't wait for the permissions to be applied before proceeding with actions which require them. The dataset, keyring, and managed zone would be marked as `depends_on` the various `google_project_service` resources which enable the relevant APIs.

#### Let's say we want to scale some workload with 100 replicas which require more resources than the cluster have. With the current setup, what are the changes that need to be made to provide more resources? is there a way to do without a manual modification?

Currently autoscaling is disabled as I didn't want to land myself a huge GKE bill if the autoscaler made bad decisions. The GKE cluster autoscaler would spin up new nodes as necessary once enabled. This would of course depend on accurate and correct resource definitions in the Kubernetes objects.

## K8s and deployments

#### How staging and production deployments could be isolated in the same cluster?

The two environments are deployed to different namespaces. With the network policies in place, there is no way for them to interact with each other.

#### It could be an issue to keep the staging and production deployments inside a single cluster?

One difficulty could be competition for resources; we would expect staging to have problems, potentially leading to high resource consumption, which would impact the available resources for the production environment. One shared resource in this setup is a shared outbound IP; if bad behaviour from staging caused it to be blacklisted, that would affect production.

It's also worth noting that storage and RBAC are non-namespaced resources; any changes to these affect the entire cluster.

#### How services deployments versioning could be managed/improved on the solution (rollouts, rollback, etc)?

This is the big difference between a setup like this and a truly production-ready deployment. Setting environment variables and keeping configuration in build scripts is not a suitable strategy.

Some of the things which need to be addressed before true production-readiness include immutability (monotonically increasing image version numbers for example), versioning on the deployment objects, reliable liveness and readiness checks, customised rollout strategies like blue/green and canaries, and integration of a full test suite.

One approach to the immutability issue is to package the deployment logic along with the current state of the codebase into a container itself, and maintaining a repository of these self-contained deployers. With proper monotonicity, this guarantees that deployments of a particular version are always exactly the same, allowing for a rollback failsafe.

#### How secrets changes could affect

Could you please clarify what you mean here? Affect what?

#### With the current solution, it could be possible that k8s schedules in as single node all replicas for a given deployment. Could this be a potential issue? if so, how it could be improved?

Yes. In the current setup a node represents a physical zone, so to schedule all replicas on one node would be a serious hit to reliability. Also, spreading a particular workload out - especially a resource-heavy one - means that resources can more appropriately be utilised, in particular reducing needs for context switching and I/O.

#### In terms of persistence for the datastore's stateful sets, what could happen if all the nodes where the deployments are scheduled disappeared?

The PVCs would remain as they are provisioned as GKE volumes. In a Deployment, the pods would be rescheduled on live nodes and the volumes reconnected, then since autorepair is enabled, the nodes that failed would be reprovisioned.

However, we're not dealing with Deployments; we're dealing with StatefulSets, which come with a one instance per node guarantee. If the node is unreachable, the master has no way to be sure whether the pod has evaporated, or is still running but unreachable. As such, it wouldn't reschedule the pod until the failed node object was removed.

#### How it could be improved?

There's the hack, which is to set terminationGracePeriod of the pod template to 0. This essentially disables the maximum-one-per-node guarantee and is suboptimal to say the least. There doesn't seem to be a best-practice answer; my solution would be monitoring logic sitting somewhere off-cluster which is capable of terminating nodes at the IaaS level and ensuring their node objects are removed from the Kubernetes state, allowing the pod scheduler to bring the stateful services back up and node autorepair to bring the capacity back in.

#### Let's say that Redis or Postgres release a patch version with some hotfix, what will be the steps to upgrade the datastores deployments without cutting off the service?

The complication comes from the fact that there needs to be at most one master. In order to keep downtime negligible, the following process would be necessary:

* Roll out one new Pod, which will become the new master. Configure it as a replication slave to the current master.
* Ensure replication is working properly.
* Once replication sync is complete, remove the old master pod from the headless service, add the new pod in its place, and promote it to master.
* Roll out new slave pods, replicating from the master headless service (which now points at the new master).

For services which support multiple-master configurations, downtime can be zero; all masters can coexist, then once replication is complete, the old ReplicaSet can be disposed of.

#### I see that all resource requests for the deployments are set on 1M and 32Mi, but not limited. Could this be an issue in the long term? if so, how it could be handled?

Yes - this is an omission. After deployment and visibility on resource consumption, more realistic requests and limits should be set to avoid high usage in one workload starving other workloads, while providing sufficient resource to serve requests in a reasonable manner.

**Comment by adoankim** [comment]
Hey @daveio, thanks for the detailed answers to the questions!.

I've just added some notes and amend the missing question.

## Development workflow

> Please explain briefly how the previous could be supported for the given solution.

<details><summary>Answer</summary><p>
I've made modifications to bin/deploy to fix the issues. The deployment methodology in use here is not scalable particularly due to the fact that meaningful configuration lives in the deployment script itself, which is a recipe for chaos at scale. Still, in the given solution, it now works properly; after deployment the script patches the image of the deployments, and issues a rollout.
</p></details>

Thanks for making the modifications, it looks good and works as described.

> And if we would need to deploy a single version, let's say staging, how this could be done?

<details><summary>Answer</summary><p>
> Similar modifications to the deployment script, which I've not done for the sake of time, but since support exists already to deploy a single environment to GKE, it could be modified similarly to the modifications mentioned above.
</p></details>

:+1:

## Infrastructure

> What are the benefits of keeping all the resource management in the same plan? and the advantages of separate it in different ones?

<details><summary>Answer</summary><p>
Since Terraform is a declarative model, having everything in the same plan allows it to compute desired state reliably. While portions of state can be imported from one plan into another, changes lose atomicity and complicate any guarantees, in turn complicating any automation or CI processes; it becomes possible to apply one plan but for another to fail. With everything in one plan, changes either apply or they don't.
</p></details>

Good point

> Applying the Terraform plan from a clean project I got the following errors. I've fixed it by adding "something" extra on those resources.
>
> How could we solve this dependency?

<details><summary>Answer</summary><p>
Explicit dependencies could be added using the depends_on operator. Usually dependencies are implicitly managed by the module, but in cases like this where those implicit dependencies are missing, Terraform won't wait for the permissions to be applied before proceeding with actions which require them. The dataset, keyring, and managed zone would be marked as depends_on the various google_project_service resources which enable the relevant APIs.
</p></details>

Exactly :+1:

> Let's say we want to scale some workload with 100 replicas which require more resources than the cluster have. With the current setup, what are the changes that need to be made to provide more resources? is there a way to do without a manual modification?

<details><summary>Answer</summary><p>
Currently autoscaling is disabled as I didn't want to land myself a huge GKE bill if the autoscaler made bad decisions. The GKE cluster autoscaler would spin up new nodes as necessary once enabled. This would of course depend on accurate and correct resource definitions in the Kubernetes objects.
</p></details>

The autoscaler accepts a min and max number of nodes that can be added/removed automatically so you could set the limit and avoid infinite scaling. And yes, as you commented, depending on the workloads definition more nodes will be spinned up or not :).

If the autoscaler determines that some nodes are not needed anymore it will remove them automatically. However, something that is important, depending on the workloads deployment configuration could prevent the autoscaler to remove the nodes. [[reference]](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler)

## K8s and deployments
> How staging and production deployments could be isolated in the same cluster?


<details><summary>Answer</summary><p>
The two environments are deployed to different namespaces. With the network policies in place, there is no way for them to interact with each other.
</p></details>

:+1:

> It could be an issue to keep the staging and production deployments inside a single cluster?

<details><summary>Answer</summary><p>
One difficulty could be competition for resources; we would expect staging to have problems, potentially leading to high resource consumption, which would impact the available resources for the production environment. One shared resource in this setup is a shared outbound IP; if bad behaviour from staging caused it to be blacklisted, that would affect production.

It's also worth noting that storage and RBAC are non-namespaced resources; any changes to these affect the entire cluster.
</p></details>

:+1:


> How services deployments versioning could be managed/improved on the solution (rollouts, rollback, etc)?


<details><summary>Answer</summary><p>
This is the big difference between a setup like this and a truly production-ready deployment. Setting environment variables and keeping configuration in build scripts is not a suitable strategy.

Some of the things which need to be addressed before true production-readiness include immutability (monotonically increasing image version numbers for example), versioning on the deployment objects, reliable liveness and readiness checks, customised rollout strategies like blue/green and canaries, and integration of a full test suite.

One approach to the immutability issue is to package the deployment logic along with the current state of the codebase into a container itself, and maintaining a repository of these self-contained deployers. With proper monotonicity, this guarantees that deployments of a particular version are always exactly the same, allowing for a rollback failsafe.
</p></details>

Good one :+1:

> How secrets changes could affect

<details><summary>Answer</summary><p>
Could you please clarify what you mean here? Affect what?
</p></details>

Sorry, I didn't notice that the question was not complete.

Let's say we have a running deployment on version 1, and we want to roll out a new version 2 with breaking changes on the secrets. For example, replacing a third-party service, and clean up of the older credentials.

How secret changes could affect older deployed versions of workload that is being rolled out?.


> With the current solution, it could be possible that k8s schedules in as single node all replicas for a given deployment. Could this be a potential issue? if so, how it could be improved?

<details><summary>Answer</summary><p>
Yes. In the current setup a node represents a physical zone, so to schedule all replicas on one node would be a serious hit to reliability. Also, spreading a particular workload out - especially a resource-heavy one - means that resources can more appropriately be utilised, in particular reducing needs for context switching and I/O.
</p></details>

Good :+1:. There is a concept called `Pod affinity & anti-affinity` that allow you to control the scheduling of your pods. For example, avoid scheduling more than 1 pod of a given deployment on the same node. [[reference](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)]

> In terms of persistence for the datastore's stateful sets, what could happen if all the nodes where the deployments are scheduled disappeared?

<details><summary>Answer</summary><p>
The PVCs would remain as they are provisioned as GKE volumes. In a Deployment, the pods would be rescheduled on live nodes and the volumes reconnected, then since autorepair is enabled, the nodes that failed would be reprovisioned.

However, we're not dealing with Deployments; we're dealing with StatefulSets, which come with a one instance per node guarantee. If the node is unreachable, the master has no way to be sure whether the pod has evaporated, or is still running but unreachable. As such, it wouldn't reschedule the pod until the failed node object was removed.
</p></details>

Good!. Extending a bit more this question, in here we let k8s to dynamically provide volume, what else we could put in place to prevent data loss?

> How it could be improved?

<details><summary>Answer</summary><p>
There's the hack, which is to set terminationGracePeriod of the pod template to 0. This essentially disables the maximum-one-per-node guarantee and is suboptimal to say the least. There doesn't seem to be a best-practice answer; my solution would be monitoring logic sitting somewhere off-cluster which is capable of terminating nodes at the IaaS level and ensuring their node objects are removed from the Kubernetes state, allowing the pod scheduler to bring the stateful services back up and node autorepair to bring the capacity back in.
</p></details>

Good one :+1:.

> Let's say that Redis or Postgres release a patch version with some hotfix, what will be the steps to upgrade the datastores deployments without cutting off the service?

<details><summary>Answer</summary><p>
The complication comes from the fact that there needs to be at most one master. In order to keep downtime negligible, the following process would be necessary:

- Roll out one new Pod, which will become the new master. Configure it as a replication slave to the current master.
- Ensure replication is working properly.
- Once replication sync is complete, remove the old master pod from the headless service, add the new pod in its place, and promote it to master.
- Roll out new slave pods, replicating from the master headless service (which now points at the new master).

For services which support multiple-master configurations, downtime can be zero; all masters can coexist, then once replication is complete, the old ReplicaSet can be disposed of.
</p></details>

:+1:

> I see that all resource requests for the deployments are set on 1M and 32Mi, but not limited. Could this be an issue in the long term? if so, how it could be handled?

<details><summary>Answer</summary><p>
Yes - this is an omission. After deployment and visibility on resource consumption, more realistic requests and limits should be set to avoid high usage in one workload starving other workloads, while providing sufficient resource to serve requests in a reasonable manner.
</p></details>
:+1:

**Comment by daveio** [comment]
@adoankim Thanks for your continued efforts. In response to your points and further questions -

> The autoscaler accepts a min and max number of nodes that can be added/removed automatically so you could set the limit and avoid infinite scaling. And yes, as you commented, depending on the workloads definition more nodes will be spinned up or not :).
>
> If the autoscaler determines that some nodes are not needed anymore it will remove them automatically. However, something that is important, depending on the workloads deployment configuration could prevent the autoscaler to remove the nodes. [[reference]](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler)

Very true. A `PodDisruptionBudget` can be put in place which is a flexible way of telling the orchestrator what you care about, what it can get away with, and what to optimise for in dealing with issues. Using one adds significant complexity, as the complex result of multiple simple rules can result in unexpected behaviours, but used conservatively they're a helpful way to give the orchestrator insight into the priorities you want it to have.

---

> Let's say we have a running deployment on version 1, and we want to roll out a new version 2 with breaking changes on the secrets. For example, replacing a third-party service, and clean up of the older credentials.

#### How secret changes could affect older deployed versions of workload that is being rolled out?.

Secrets are not inherently versioned, so without taking some action the credentials would apply to all newly-created objects which reference them. An important qualification here is 'newly-created', as any pods from the older deployments would not pick up on the changes. However, if the deployment for the older version were updated or rolled back out, newly created pods would reference the new secret.

One approach is to version secrets in their names, even if just with UNIX time as an integer. If a new deployment refers to `app-credentials-1569087597` then there's no way it can cause issues for an older deployment referencing `app-credentials-1482958597`.

---

> There is a concept called `Pod affinity & anti-affinity` that allow you to control the scheduling of your pods. For example, avoid scheduling more than 1 pod of a given deployment on the same node. [[reference](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)]

While I didn't implement them here I do actually use them on my own personal cluster, a snippet:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
[...]
spec:
  [...]
  template:
    [...]
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dave-io
            topologyKey: "kubernetes.io/hostname"
[...]
```

This configuration ensures that only one pod matching `app=dave-io` exists per instance of `kubernetes.io/hostname` (ie, per node).

---

#### in here we let k8s to dynamically provide volume, what else we could put in place to prevent data loss?

We can set the `persistentVolumeReclaimPolicy` to `Retain`, which will keep the disk images around rather than cleaning them up if the PVC is destroyed. That has its own consequences, though, ie the fact that old volumes lying around still have to be paid for. Monitoring for the environment would need to include checks for any PVs with their status in the `Released` state so that any cleanup can be taken care of.

It's also well worth enabling snapshotting at the GCP level for persistent volumes, especially those which don't change much but the changes are meaningful, for which the additional cost of deltas will be low and the benefit in terms of recovery high. Snapshots could be taken at regular intervals, or even in response to application events through platform automation.

None of the above are any substitute for a fully application-aware backup strategy. They are 'if all else fails' measures which do not guarantee successful recovery in all cases. An example might be {My,Postgre}SQL databases, which cannot guarantee usability of a point-in-time snapshot of the binary database state - only application-aware backups can provide that.

**Comment by adoankim** [comment]
hey @daveio, Thanks for the answer to the questions!. I've got nothing else to add.

I'll check with the team if there is any other review of the PR is on progress, or if we can proceed with the next steps.

**Comment by daveio** [comment]
@adoankim Ace, thanks. Looking forward to hearing from you.

**Pull request closed without merging**
